### ISSUE TITLE
(Mod Compat) Suggestions!

### ISSUE THREAD

**Issue by CorgiTaco** [CorgiTaco/Better-Weather#1]
From Curse: "Any chance of compact with Mekanism 10? Maybe acid rain is caused when there is radiation in the atmosphere and it begins to rain?"

**Comment by bessiq** [comment]
Relevant:

https://youtu.be/npjF032TDDQ

**Comment by Silvrus** [comment]
I was looking for a mod that would stop sleeping from clearing weather. You would still be able to sleep to skip night, but it wouldn't affect the weather, so it would continue raining and snowing. Is that something you might be interested in doing?

**Comment by laserlemons** [comment]
A suggestion I have is to make use of the new freezing effect from the 1.17 snapshots during a blizzard.

**Comment by cyberpunkbln** [comment]
@Silvrus Yes so a mod i search, too. I have made a crippled Datapack where i start the rain randomly new,when i wake up. I know only one big Mod for older Version that deactivate the wheather reset on sleep, Dynamic Sounds, has an option reset rain on sleep. But his is a very old mod, the new mod ambient sounds don't have so an option.

**Comment by Corvus20** [comment]
More of a general suggestion, but ties into mods as well. When a sandstorm happens, the color of the particles will be pulled from the main sand block in the biome. So a red sand biome would have red sandstorms, the Quartz desert nether biome would have white ones, etc. This was a flaw with Corosus' Weather, Storms, and Tornadoes mod as it only used the normal tan-yellow sand, which made some biomes look really messed up afterwards. Also making it so the Tumbleweeds from the Tumbleweeds mod spawn more frequently during a sandstorm.

**Comment by GnomTocha** [comment]
Привет. Присутствует ли поддержка смены сезонов с мода serene seasons?

**Comment by GnomTocha** [comment]
> Привет. Есть ли поддержка смены сезонов в моде serene seasons?

edited language

**Comment by Corvus20** [comment]
Adding on to/re-explaining my last ideas:

-Snow Real Magic compatibility (unless it already works just fine)

-Sandstorm effects, particles and accumulating sand piles (if being implemented) should take the texture from the main sand block of the biome, so red in red deserts, tan-orange in the Atmospheric mod's dunes biome, white in quartz deserts, etc.

-Tumbleweeds from the Tumbleweeds mod spawn more frequently during a sandstorm if they spawn in said biome.

-Making weather types configurable to occur in different dimensions. So once Galacticraft or Advanced Rocketry updates, we can have sandstorms on Mars or acid rain on Venus.

-Leaves/Petals blowing in the wind. Based on the biome's foliage color, cherry petals, autumn leaves, etc. will occasionally drift in the breeze like in Coro's Weather 2 mod.

-Foggy weather: the area is covered in a thick fog, with varying levels of density. Biome fog tweaks added by other mods will effect the fog.

-Spore Bloom: A special weather type in mushroom biomes, greenish-tan fog with small spore particles covers the biome, and mushrooms have a chance to sprout, and non-giant mushrooms have a chance of growing into giant mushrooms.

-Ash Snow: Nether biomes such as the Basalt deltas can have a rare increased ash snow event, with piles of ash building up, black-grey fog, and just being spooky.

-Windy Weather: inspired by the even in Terraria's 1.4 update. Foliage precipitation (leaves, petals, etc.) occur more often, and in deserts occasional drifts of sand particles and more tumbleweeds are seen.

-Endergetic Expansion compatibility: Poise Bloom weather with light purple fog and the purple bubble particles seen in that biome, increased puffbug activity. Boloom fruit now sway in the wind.

**Comment by TechTastic** [comment]
Support/Compatibility with Serene Seasons and/or Tough As Nails/SimpleDifficulty/etc.

**Comment by Corvus20** [comment]
Pollution of The Realms has updated to 1.16. Making it so acid rain will only occur based on pollution factors from that mod would be cool if not already integrated.

**Comment by Corvus20** [comment]
Better compatibility with Dynamic Surroundings, Charmonium, and other ambience mods. Currently when it is cloudy weather Dynamic Surroundings thinks its rain and plays the rainy mud footsteps sounds, the same goes for blizzards, and that doesnt seem quite right.

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
