### ISSUE TITLE
BetterWeather seasons config not working

### ISSUE THREAD

**Issue by FurryApocalypse** [CorgiTaco/Better-Weather#11]
The latest update for 1.16.4 (1.1.1)
I changed the time of season to make it longer. A lot longer. Config was totally ignored several times. should be like 20 days for sub season, and it keeps changing every 3 days.

Position in config

#Better Weather Settings
[Season_Settings]
	#The length of each season in ticks. 24000 is a single minecraft day!
	#Default: 240000(10 Minecraft days)
	#Range: > 24000
	SeasonLength = 1728000
	
	Also i dont see any other config for subseasons. :/

**Comment by frank89722** [comment]
I think not only seasons config not work properly.
I have tried to disable acid rain destroy blocks, but it still destroys blocks. 
I also remove PLAYER from the acid rain EntityTypes, but players still getting damage.

**Comment by CorgiTaco** [comment]
Are you using the config located in /better weather folder?

**Comment by frank89722** [comment]
Yes. I also removed the old config file

**Comment by FurryApocalypse** [comment]
So im not the onlyone. I had to delete betterweather due to those porblems. Could not pair it with serene seasons at all even when time was calculated 1-1 . Configs just dont care bout it

**Comment by CorgiTaco** [comment]
https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3161729
