### ISSUE TITLE
Serene Seasons

### ISSUE THREAD

**Issue by ChronosForkyMason** [CorgiTaco/Better-Weather#12]
Does this work with Serene Seasons?  If so what is different between using this and serene seasons?  If not then there should be compatibility made between these two mods so they don't clash with each other.

**Comment by CorgiTaco** [comment]
probably but the results would be weird

**Comment by ChronosForkyMason** [comment]
Would you happen to know what happens when Serene Seasons and this mod are installed together?

**Comment by CorgiTaco** [comment]
try

**Comment by ChronosForkyMason** [comment]
It would seem that it can be two seasons at the same time.  You can be both spring and summer at the same time.  This seems to because the Serene Seasons' seasons are different than the seasons from Better Weather.  I would recommend that when the season changes in this mod it should set the season of the other mod to match.  Also, the seasons from both mods should be the same number of Minecraft days.  Also, the senor from Serene Seasons does not detect the season from this mod and should.  Either way, some integration between this mod and serene seasons needs to be done so the seasons match and so we only have one mod controlling the season changes.
