### ISSUE TITLE
Villagers don't take damage from acid rain.

### ISSUE THREAD

**Issue by OutlandJoe** [CorgiTaco/Better-Weather#13]
I understand this may be a style choice, but I would really appreciate it if you added the ability to let villagers take damage from acid rain considering their zombie variants take damage. There's a lack of mods that straight up kill villagers naturally, this mod would be great for a dystopia where for once villagers can die! Would greatly appreciate this, and keep up the good work!

**Comment by OutlandJoe** [comment]
When I say "ability" I meant an optional choice in the config like "ANIMALS,PLAYERS,MONSTERS" and then "VILLAGERS" considering some people would likely like/dislike it if their villagers were immortal to acid rain.

**Comment by CorgiTaco** [comment]
Configurable in latest beta, add the villager id to the entityDamage map in the `betterweather-acid_rain` config
