### ISSUE TITLE
Chunk Pregen compat request.

### ISSUE THREAD

**Issue by Speiger** [CorgiTaco/Better-Weather#18]
Hey,
I just got a incompat for Better Weather and ChunkPregenerators Preview Feature.
The Preview adds a Custom Server but does not add a World or a Player to the client because they do not exist.
Sadly adding that is not really possible since it is a server running in the background.

The incompat is this line:
https://github.com/CorgiTaco/Better-Weather/blob/6ab27ba01ab48df9f580eb0e08f705a6fef0e81d/src/main/java/corgitaco/betterweather/season/client/BiomeColorCalculator.java#L33
Since the World is null then your mod Crashes.

I have 2 possible fixes for you:
1. check if the client world is null if that's the case return the default color.
2. 1 but if the world is null you check if a server exists if it is the case grab the dynamic registries from there. Otherwise default color. that would be:

```java
   public static Color modifyBiomeColor(ColorType colorType, Color originalColorValue, Season.SubSeason subSeason, Biome biome) {
        Color fallbackColor = modifyColorForWeatherEvent(colorType, originalColorValue, originalColorValue, null);

        if (!BetterWeather.useSeasons)
            return fallbackColor;

	ClientWorld world = Minecraft.getInstance().world;
	DynamicRegistries registry = world == null ? null : world.func_241828_r();
	if(world == null) {
		MinecraftServer server = ServerLifeCycleHooks.getCurrentServer();
		if(server == null)
		     return fallbackColor;
		dynamicRegistries = server.func_244267_aX();
	}
	if(dynamicRegistries == null)
	    return fallbackColor;
        ResourceLocation biomeKey = dynamicRegistries.getRegistry(Registry.BIOME_KEY).getKey(biome);
            if (biomeKey == null)
                return fallbackColor;
	}
```

if you don't want to do that. That is fine too, I will then just link the config setting that needs to be changed to fix the issues that could be done instead.

Thanks for reading. Speiger

**Comment by Speiger** [comment]
@CorgiTaco Thanks for the patch

**Comment by CorgiTaco** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3173146
