### ISSUE TITLE
Mod Compat (SereneSeasons) + Bug + Question

### ISSUE THREAD

**Issue by MegaGamer265** [CorgiTaco/Better-Weather#19]
It would be cool if it works together with serene seasons!

Also i have a question. In the settings you can set the length for a season. So does it mean the whole season or subseason?

And also a bug. When i cheat the blizzard weather then it only plays the sound where i stand and not everywhere.

**Comment by CorgiTaco** [comment]
I think this a case of either Serene Seasons or Better Weather since Better Weather has its own season system. And that bug will be patched in today's patch

**Comment by CorgiTaco** [comment]
And it's the whole season
