### ISSUE TITLE
Snow pile up

### ISSUE THREAD

**Issue by MegaGamer265** [CorgiTaco/Better-Weather#21]
When snow is piling up to 1 block high i can`t remove it with water bucket. And my fear is it won`t melt in spring.

**Comment by CorgiTaco** [comment]
itll melt in all seasons that arent winter

**Comment by MegaGamer265** [comment]
![2021-01-19_00 28 11](https://user-images.githubusercontent.com/47698400/104970874-484c1900-59ed-11eb-86bf-d1f053c50aeb.png)
 
Sadly if the piles are to high they from a whole snow block and not a fully piled up snow.
