### ISSUE TITLE
Start up crash

### ISSUE THREAD

**Issue by Alexander175** [CorgiTaco/Better-Weather#22]
Getting a startup issue. Using the latest version of forge for 1.16.5.

Crash Report
[crash-2021-01-18_18.04.24-fml.txt](https://github.com/CorgiTaco/Better-Weather/files/5833216/crash-2021-01-18_18.04.24-fml.txt)

**Comment by CorgiTaco** [comment]
Try this and lmk if it works: https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3173271

**Comment by Alexander175** [comment]
> Try this and lmk if it works: https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3173271

Just tried it, Its working great. Thanks :)
