### ISSUE TITLE
Better Weather 1.2.2 Crash on entering a world

### ISSUE THREAD

**Issue by frank89722** [CorgiTaco/Better-Weather#24]
I had reset the config. 
But I'm on mc 1.16.5(forge 36.0.1)

Crash report: https://gist.github.com/frank89722/064a6b86430c262c438f5a63c1959e5f

**Comment by CorgiTaco** [comment]
Try v1.2.3: https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3173417

**Comment by CorgiTaco** [comment]
LMK if it works

**Comment by frank89722** [comment]
It's work!
Man, you're so good <3
