### ISSUE TITLE
[1.16.1] client crashes when joining server

### ISSUE THREAD

**Issue by bessiq** [CorgiTaco/Better-Weather#3]
Forge: 32.0.108
Better Weather 1.0.1 MCV: 1.16.1

First of all, let me preface this issue by saying how absolutely worthless Minecraft logs can be sometimes. Anyway, I finally stopped putting off testing my pack on a dedicated server, which went pretty okay until I tried to join the world. When I attempted to join, I'd simply be yeeted off and my client would crash to desktop. It would say Joining World, then Saving World, then bye-bye Minecraft. The server log acts like nothing happened whatsoever, and continues to merrily chug along.

After hours of "dividing and conquering" my mod list, restarting the client and the server, and trying to log in, I discovered I can only log in to the world if I disable Better Weather. (This would've admittedly taken less time if I didn't already have over 200 mods.) Anyway, I shall provide the client logs since they may have info you can use, and I can provide server logs if you think it's necessary. But it seems like it has something to do with client rendering of...stuff.

The crash log, which makes no mention of BW in the error: https://hatebin.com/vqifttqako
The latest log, which seems relevant starting at line 2181: https://hatebin.com/rtnfvzrprc

I'm waiting for Forge 33 to get out of alpha and will move to 1.16.2 once it's feasible, so if this is something you don't want to bother with for 1.16.1 I can live without it temporarily. Thanks!

**Comment by CorgiTaco** [comment]
Uhhhh you chopped the latest.log lmao

**Comment by bessiq** [comment]
Lame, it showed the whole log for me when I saved it, but opening the link I see hatebin did chop it. 

Here is the last part of the latest.log: https://hatebin.com/zqszquhttc
And here is the whole enchilada: https://www.dropbox.com/s/wf9zo5gs0yyy4wn/latest.log?dl=0

**Comment by Moonflowey** [comment]
Also having the same issue. Immediate crash upon joining a server. Singleplayer is completely fine, though.

**Comment by CorgiTaco** [comment]
Fixed here: 
[Forge 1.16.1] https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3046156

[Forge 1.16.2] https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3046159
