### ISSUE TITLE
Incompatibility with Clear Skies

### ISSUE THREAD

**Issue by Boymann** [CorgiTaco/Better-Weather#30]
Here is the crashlog, when removing Clear Skies, the issue is resolved.
[crash-2021-01-21_23.39.44-client.txt](https://github.com/CorgiTaco/Better-Weather/files/5852528/crash-2021-01-21_23.39.44-client.txt)

**Comment by CorgiTaco** [comment]
The issue would be in this class specifically, but unfortunately this seems to be a case of either Better Weather or Clear skies, you can also achieve a similar effect by utilizing the season config and setting the target foghex color to "78A7FF" and setting the fog blend strength to 1.0!

**Comment by CorgiTaco** [comment]
Whoops i forgot to link the class: https://github.com/Jarlish/clear-skies-forge/blob/main/src/main/java/jarl/clearskies/mixin/MixinBackgroundRenderer.java#L42-L45 vs Better Weather's: https://github.com/CorgiTaco/Better-Weather/blob/Forge-1.16.X/src/main/java/corgitaco/betterweather/mixin/client/MixinFogRenderer.java#L13-L16
