### ISSUE TITLE
Sinking into snow (Suggestion)

### ISSUE THREAD

**Issue by MegaGamer265** [CorgiTaco/Better-Weather#32]
When the snow is deep you walk really slow and sinking into it.

**Comment by Mysticpasta1** [comment]
Isn't this just the powdered snow from 1.17?

**Comment by Mysticpasta1** [comment]
It would be nice to have that.

**Comment by CorgiTaco** [comment]
This will be postponed for 1.17 since we'll take advantage of vanilla's powdered snow block

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
