### ISSUE TITLE
Snow and Grass (Suggestion)

### ISSUE THREAD

**Issue by MegaGamer265** [CorgiTaco/Better-Weather#34]
is it possible that layered snow does not make grass blocks into dirt blocks?

And maybe in spring flowers and grass respawn after the snow removed them in winter.

**Comment by CorgiTaco** [comment]
This is something difficult to do, but I could look into it!

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
