### ISSUE TITLE
Serene Seasons compatibility: Snow with rain in warm biomes during winter

### ISSUE THREAD

**Issue by Vojife** [CorgiTaco/Better-Weather#39]
When Serene Seasons is installed and it's winter in a biome where it normally rains, with weather on DEAFULT or DEFAULT_THUNDER, visually it snows and rains at the same time, the rain makes no sounds. Other weathers do not change to snow at all in these conditions.
It would be great if this compatibility was somehow added, although I know it's not really this mod's standalone issue.

**Comment by CorgiTaco** [comment]
We use our own seasons so no
