### ISSUE TITLE
Mod compatibility

### ISSUE THREAD

**Issue by Globox1997** [CorgiTaco/Better-Weather#4]
Hey CorgiTaco,
Could you release a fabric version on github to use jitpack to add mod compatibility? :D

**Comment by CorgiTaco** [comment]
what in the world is that

**Comment by Globox1997** [comment]
[https://jitpack.io/](https://jitpack.io/) never head about it?

**Comment by CorgiTaco** [comment]
Nah, do you think you could PR this? I'm not sure how implement this correctly, and additionally I'm busy with other projects atm

**Comment by Globox1997** [comment]
oh I didn't mean to change any code, just a fabric release like you did here [https://github.com/CorgiTaco/Better-Weather/releases/tag/v1.0](https://github.com/CorgiTaco/Better-Weather/releases/tag/v1.0)
Is it working for 1.16.2+ btw?

**Comment by CorgiTaco** [comment]
Oh so just a dev/srcs jar? I can do that here in a few

**Comment by Globox1997** [comment]
yea :)

**Comment by Globox1997** [comment]
So there has never been a release but no need for an open issue :)
