### ISSUE TITLE
Crash when joining server

### ISSUE THREAD

**Issue by kmorales13** [CorgiTaco/Better-Weather#41]
[crash-2021-03-17_23.31.36-client-1.txt](https://github.com/CorgiTaco/Better-Weather/files/6161628/crash-2021-03-17_23.31.36-client-1.txt)

Related to #16 

Using Better Weather 1.2.9 MCV: 1.16.4/1.16.5

**Comment by CorgiTaco** [comment]
did you try Better weather alone?

**Comment by LegoLoverGo** [comment]
https://github.com/CorgiTaco/Better-Weather/issues/16#issuecomment-798993889

This issue also persists on Linux.

**Comment by CorgiTaco** [comment]
This issue should no longer occur in the latest beta
