### ISSUE TITLE
Issue with grass textures

### ISSUE THREAD

**Issue by TotallyMephi** [CorgiTaco/Better-Weather#42]
I don't quite know how to explain this, but grass textures are randomly a different colours. Sometimes it doesn't happen for several biomes and then it can happen en masse. I'll provide a screenshot for a better example, but this issue seems to disappear entirely when I remove this mod from my load order.
![2021-03-20_09 24 41](https://user-images.githubusercontent.com/80362344/111865992-26760080-8962-11eb-8930-9b19a3d938d6.png)

**Comment by CorgiTaco** [comment]
Did you try F3+A?

**Comment by TotallyMephi** [comment]
> 
> 
> Did you try F3+A?

All that seems to do is just move the issue to another area in the rendered chunks, sometimes worse, sometimes better, but never fully gone.

**Comment by CorgiTaco** [comment]
This is a vanilla bug: https://bugs.mojang.com/browse/MC-173723
