### ISSUE TITLE
Better Weather Failed To MixinApply

### ISSUE THREAD

**Issue by Klouver0X** [CorgiTaco/Better-Weather#44]
https://paste.gg/p/anonymous/a45b862930b0428982d337814d2a5076

also sorry for putting in the wrong Mod Issue. Please don't take my Canned Bread away

**Comment by Klouver0X** [comment]
https://paste.gg/p/anonymous/0f2f6cbd8db94ed89f3366a150980e55

I tried the the New Beta you released still crashed

**Comment by CorgiTaco** [comment]
fixed

**Comment by Klouver0X** [comment]
YAY! I get to keep my Canned BRead
