### ISSUE TITLE
Tiny Bug in BiomeColorCalculator (Got reported through ChunkPregen)

### ISSUE THREAD

**Issue by Speiger** [CorgiTaco/Better-Weather#47]
Basically this null check
https://github.com/CorgiTaco/Better-Weather/blob/Forge-1.16.X/src/main/java/corgitaco/betterweather/season/client/BiomeColorCalculator.java#L32

happens after:
https://github.com/CorgiTaco/Better-Weather/blob/Forge-1.16.X/src/main/java/corgitaco/betterweather/season/client/BiomeColorCalculator.java#L26

That causes a crash with chunkpregen, because the world is null but the world null check happens when its to late.

Thanks for reading.

Speiger

**Comment by CorgiTaco** [comment]
This *should* be fixed in the latest beta
