### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by TheTipsyGamer** [CorgiTaco/Better-Weather#48]
I'm unsure if it's just the commands but it'll let me put in the commands for the mod so I think the mod is being recognized but just isn't working. The mods I have downloaded are Optifine, Forge, Survive, UnionLib, Simple Backpack and Toolbelt. I have tried to set the java file destination to the one I downloaded as well as attempted the AdoptJDK thing on the mod page. I'm not sure what information anyone would need but just would like a direction to go to make this work. On all the mods(even the working ones) it is saying that the signature is Unsigned and Trust:None. Idk if that'll help but like I said, any direction would be nice. I just want nice weather stuffs

**Comment by CorgiTaco** [comment]
Should be fixed in latest beta
