### ISSUE TITLE
Cannot execute betterweather in data pack

### ISSUE THREAD

**Issue by cyberpunkbln** [CorgiTaco/Better-Weather#49]
Hi,

when i try to execute betterweather setweather betterweather-DEFAULT in my data pack:
`
execute if score @p rr.weather matches 2 run betterweather setweather betterweather-DEFAULT_THUNDER`

Minecraft/Forge-Log says:
`
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 7: Ungültiges Befehlsargument at position 51: ...hes 1 run <--[HERE`]

Internal minecraft commands functioned very well 

?
thx

Edit: The Problem is sleep reset the weather and rain and storm will never appear, when i sleep:(. It gives no Mods for 1.16 that deactivate the sleepResetRain-Ag from Minecraft and only data packs that use her own weather callings, but this datapacks call the origin weather commands ...

**Comment by CorgiTaco** [comment]
Could you try this in the latest better weather beta?

**Comment by CorgiTaco** [comment]
No response. Closing...
