### ISSUE TITLE
[1.16.5] Better Weather not registering as season provider

### ISSUE THREAD

**Issue by XxInvictus** [CorgiTaco/Better-Weather#55]
Receiving the below in server log, not sure if this is intended activity but Better Weather is not registering with Forge as a season provider:
`[27May2021 13:29:59.675] [modloading-worker-6/INFO] [CRT/]: Setting *DEFAULT* builtin as default season provider
...
...
...
[27May2021 13:33:46.707] [Server thread/INFO] [CRT/]: Season provider and tracking is disabled (not required by any mod) [FINAL]`

**Comment by CorgiTaco** [comment]
what is this...?

**Comment by CorgiTaco** [comment]
No response/not enough information. Closing.
