### ISSUE TITLE
Stuck on 0% world loading

### ISSUE THREAD

**Issue by agentwolf88** [CorgiTaco/Better-Weather#58]
Stuck on 0% world loading.

mc 1.16.5
betterweather-2.0-BETA-SEASONS-ONLY-4.jar
forge 36.1.13

https://paste.ee/p/t8UN0

[latest.log](https://github.com/CorgiTaco/Better-Weather/files/6571749/latest.log)

**Comment by TeamPolus** [comment]
I have the same issue, which mods u have?

**Comment by agentwolf88** [comment]
I use my own modpack...

[Unbenannte Datei.txt](https://github.com/CorgiTaco/Better-Weather/files/6663058/Unbenannte.Datei.txt)

**Comment by TeamPolus** [comment]
I think it might be a issue with advanced rocketry but i am not sure.

**Comment by agentwolf88** [comment]
I will try it later.

**Comment by agentwolf88** [comment]
Nope, Advanced Rocketry is not the problem.

**Comment by arketec** [comment]
I am also having this issue. I suspected it was Pollution of the Realms, but I noticed you dont have that in your list, but it might the it's companion mod, which is advanced chimneys that is causing the issue.

**Comment by agentwolf88** [comment]
With the latest version it works fine. You have to delete the config file!
