### ISSUE TITLE
[Suggestions] Various ideas/suggestions. pick what you like :)

### ISSUE THREAD

**Issue by AlienXtream** [CorgiTaco/Better-Weather#60]
settings/gamerules

    starting season (simple and sub seasons)
    
    DoWeatherGriefing = true/false. prevents any and all season/weather effects from changing blocks in the world (crop growth 
    can be reversed but never breaks crops)
    
    weather griefing specifics (config). settings for forming snow, ice, thawing, crop/grass damage, leaf decay and more. anything 
    that would cause a block to break or (re)place.
    
Features (gameplay/utilities)
   Calendar - shows the day of the year (days passed with rollover at end of mod year/season cycle) and current (sub)season
   
   Forecaster - shows current weather as well as the next 3 days MAJOR weather events.
   
   Weather events - mod chooses the weather and duration in advance (rather than via RNG which i assume vanilla does). major 
       events happen at most once per day with a random lesser event after (e.g blizzard -> snow -> cloudy -> clear). Major events
       can last several days
   
   Sunburn - staying out during the day without armour on gives a sunburn debuff that increases damage taken for a time. cured 
       by either instant health or regeneration effects (they are after all magic potions so should instantly fix them in lore right? :P)

  Variable sun set/rise - self explanatory 
       
Events
   Monsoon. heavy rainstorm with lots of thunder and lightning. fills holes exposed to sky with water up to sea level. also creates
   puddles (both configurable). restricted to tropical or hot climates. outside them just the heavy rain and lightning happen

   Typhoon. tornado like storm that forms at sea and moves in land for a while. will suck up any entities into its vortex. block 
   destruction optional (default off)
   
   cold snap. abnormally cold temperatures in warmer seasons. 
   
   heat wave. very hot. player will take damage if they stay out of water (and not in caves/underground) for too long. death 
    message "'player' died from heat exhaustion" or alternatively "'player' forgot to cool off on a sunny day"
   
   
   Wind- variable direction of wind. blowing most particles in said direction as well as adjusting minecraft clouds speed and movement direction (if thats possible somehow). 
   
   Fog. colder seasons have dense fog sometimes that can make navigating near impossible. 
   
   gale force winds. extreme winds that will slow down players walking into it and speed them up (or even blow them away) walking with it. mobs unaffected for lag and practicality reasons.

dimension specific weather. 
nether- "howling gust"- hot wind that has an eeriness to it. flows towards lava lakes and open areas, slightly pushing entities in its path, as if trying to push the player to their demise.
             "chilling wind" - cold gust that near freezes you in place. lasts a day or two.

End- "ender storm" big swirling storm that engulfs the end island, preventing players from leaving any way but the gateways. during dragon fight periodic bolts of lightning will dance across the sky
       ender thunder - when its "raining" the end sky lights up with bolts of lightning (and ball lightning). occasionally lightning will strike within 32 blocks of a player. 

Wither's storm (separate from the wither storm from the spin off game. note the POSSESSIVE 's' ;p )
     local storm that forms around the wither fight if in the overworld/sky visible (to avoid issues with wither farms/chambers). t will prevent the wither leaving the area as well as discourage players entering/leaving the zone by giving slowness when passing through the barrier. the longer the wither is left alive the worse the storm gets. starting with just a darkened sky next there is toxic rain (poison players every now and then) then wither rain (wither players every now and then). 5 mins each giving a 15 min time frame to kill the wither. 
Misc 

 lightning strikes flying or high up players as well as trees if a player goes under one. "grounding" enchantment to reduce lightning damage and, if struck in the air (elytra/creative flight), discharge that energy to the next entity hit for an extra half heart or when touching the ground (zapping entities in a 1 block radius for 1/2 hearts each). 

  mod compatibility options for mods that add player temperature/thirst (if its not already a thing). one example in 1.16.5 is 
  "Survive"
  
  option for leaf blocks to "fall" in autumn (turning orange and then invisible. would likely have to be hand made textures and so 
  mod compatibility would be limited to ones that use the vanilla textures too, though instructions for what a player needs to do 
  to create their own for 3rd party patches/resource packs). default off. 
  
  Blizzards pile snow layers up next to solid blocks.
  
  snow can form on stairs and slabs. if it does, and the player disturbs them it will "slide" down the stairs and fall onto the ground, 
  stacking up layer by layer.
  
  sibling mod adding gear for handling weather effects safely (straw/beach hats, sunscreen, curio slot coats, snow shoes, snow 
  shovels. 
  
  legendary trident of Poseidon. found in the heart of a typhoon. dangerous and near impossible to get at. enchanted 
  with unique "Wrath of Poseidon" and custom loyalty that always returns to the owners inventory if lost (void or 
  despawn/delete) (can not have others added) which lets the player swim fast, waterbreathing underwater and when used during 
  a thunderstorm or typhoon summons either lightning bolts OR a small, non griefing, typhoon that pulls in close mobs and 
  flings then into the air (lasts until picked up) respectively or a whirlpool underwater that pulls other mobs down (like a bubble 
  column but MUCH more aggressive. not faster though, just harder). drowned also wont attack you while holding it. is 
  unbreakable
  
  Pollution of the realms compat (it has an acid rain feature in polluted chunk)
  
  weather vain

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
