### ISSUE TITLE
Snow problem

### ISSUE THREAD

**Issue by owl7777** [CorgiTaco/Better-Weather#64]
In winter, snow appears everywhere but in summer it does not melt, and I have to clean whole Meadows biome from Biomes'O Plenty, and other nearby biomes from mods like BYG.

**Comment by CorgiTaco** [comment]
Yup this is a very complex issue to tackle due to the hundreds of variables that exist

**Comment by Sythalin** [comment]
Was just coming to post this as well.  2 snowstorms later and our map is now pretty much perma-snow.  As it would take too much work to remove it all, I'm gonna be recommending to our admin to reroll the world and remove this mod til a fix comes.

We love the concept, but right now this is "game breaking" enough to do without for the time being.

**Comment by Trinsdar** [comment]
Maybe i'm wrong here, but couldn't you simply mixin into the snow layer block and make it possibly remive itself in non winter seasons through rand ticks?

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
