### ISSUE TITLE
WorldRenderer Crash

### ISSUE THREAD

**Issue by WenXin20** [CorgiTaco/Better-Weather#65]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Better Weather v2.0-beta.4`

When using the command `/betterweather setweather betterweather-acid-rain 5000`, my game immediately crashed.
[Crash Report](https://gist.github.com/WenXin20/fcbd451fb3727efc6e0c97c3edfe334d)

**Comment by CorgiTaco** [comment]
Does this issue persist in the latest beta?

**Comment by WenXin20** [comment]
Yep, tried the release 2.0 with no other mods, but still crashed.
https://gist.github.com/WenXin20/b0a0f2abb396ba04be87d472f2c4879b

**Comment by WenXin20** [comment]
Resetting the config seems to have fixed it. :)
