### ISSUE TITLE
Shelter does not prevent slowness, fog, and circle particles from blizzard

### ISSUE THREAD

**Issue by Inonedn** [CorgiTaco/Better-Weather#7]

**Comment by CorgiTaco** [comment]
The issue of fog is the only relevant bug currently in the latest betas.

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
