### ISSUE TITLE
forger version error

### ISSUE THREAD

**Issue by portalxd6** [CorgiTaco/Better-Weather#74]
anyone on this earth can you give to how to fix the forge 36.0.5 error ı only have forge 36.0.0 1.16.5 version

**Comment by CorgiTaco** [comment]
Download the latest forge from forge's website

**Comment by portalxd6** [comment]
can you give the download link 36.0.5 1.16.5 version forge ı cant found anywhere

**Comment by portalxd6** [comment]
did you update to weather mod to forge 1.17.1?

**Comment by portalxd6** [comment]
oh ı get it

**Comment by portalxd6** [comment]
oh old version get update ı didnt know that i think directly update to 1.17.1

**Comment by portalxd6** [comment]
sorry for that nevermind problem solved!

**Comment by portalxd6** [comment]
sorry for bad engilish

**Comment by portalxd6** [comment]
thank for ruining my day and broke my forge

**Comment by portalxd6** [comment]
ıts stucks on safe mode every time ı try to load

**Comment by CorgiTaco** [comment]
probably another issue then, what you should do is send a latest.log
