### ISSUE TITLE
Biome color looks weird in summer after disable weather changeBiomeColors

### ISSUE THREAD

**Issue by frank89722** [CorgiTaco/Better-Weather#75]
betterweather-2.0

Before disable `changeBiomeColors` in _weather-settings.toml_:
![2021-08-01_17 47 28](https://user-images.githubusercontent.com/10683361/127766646-6438a66c-4ed2-4b5d-9082-71b6910b5f31.png)

After:
![2021-08-01_17 45 13](https://user-images.githubusercontent.com/10683361/127766580-65347fea-a308-45e8-94bc-ee9219f5c19d.png)

Seems like this only happen in Summer

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
