### ISSUE TITLE
[1.16.5][Crashing Bug] Mod incompatible with pokecube berries with betterweather ticks

### ISSUE THREAD

**Issue by dreckz** [CorgiTaco/Better-Weather#77]
Crash report: 
[crash-2021-08-03_09.00.24-server.txt](https://github.com/CorgiTaco/Better-Weather/files/6924641/crash-2021-08-03_09.00.24-server.txt)

I have other mods as well but the crash report looks to mainly clash with the berry.

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
