### ISSUE TITLE
Little Bug when doing commands manually

### ISSUE THREAD

**Issue by cyberpunkbln** [CorgiTaco/Better-Weather#8]
Hello,

only a little bug. I have made a datapack where i use an random var to let it rain when i wake up and now i have inserted Better Weather with the commands for blizzard and acidrain. But when i do it manually both blizzard and acidrain, the raining particles are green again, when i use /weather rain or thunder. The color will not be reset. Every time it rains it rains green without poisoning.

I don't know if it bugged when i let the acidrain naturally spawn.

thx.

Edit: a little question: is it possible to run an command from an minecraft foreign mod like yours?

execute if ... run betterweather blizzard?

**Comment by CorgiTaco** [comment]
Restarting your game typically fixes this issue. Is this forge or fabric? What version?

**Comment by cyberpunkbln** [comment]
This is the Forge Version 35.0.1. Yes restart fix the issue. But i don't can run your commands in an datapack with execute .. run betterweather. He disabled the whole datapack as broken. I think this is a limitation of the datapacks-mcfunctions.

When you know or coding an little Option in your mod that sleeps don't reset rain, it was the coolest mod since years:). When i sleep the whole weather will be resetet and i don't see bliizards only when i don't sleep and my datapack don't can trigger the events blizzard or acid rain.

**Comment by CorgiTaco** [comment]
Should be fixed for sure now
