### ISSUE TITLE
Channeling not working

### ISSUE THREAD

**Issue by LeKripiY** [CorgiTaco/Better-Weather#81]
Hey, I've found an issue with all of the thundering weathers, i got a trident with channeling but it isn't working when i throw it on mobs and also I don't seem to find natural lighting strike either.
And quick question is Immersive Engineering supported ? (the lighting rod)

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
