### ISSUE TITLE
Screen flashes on weather change

### ISSUE THREAD

**Issue by ITCMD** [CorgiTaco/Better-Weather#83]
Whenever the weather changes, it looks like its reloading the chunks or something, the screen flashing as it refreshes whenever the weather changes.

[Game log](https://github.com/CorgiTaco/Better-Weather/files/7050932/latest.log)

Mod list:

[mods.txt](https://github.com/CorgiTaco/Better-Weather/files/7050935/mods.txt)

**Comment by Potoato** [comment]
I have this same problem too

**Comment by ITCMD** [comment]
This can be fixed by setting `ChangeBiomeColors` to false in `config\betterweather\minecraft\overworld\weather\weather-settings.toml`
