### ISSUE TITLE
Snow not melting in spring

### ISSUE THREAD

**Issue by ITCMD** [CorgiTaco/Better-Weather#84]
Perhaps I'm just not giving it enough time, but after a blizzard the snow has not melted as of 5 days from the end of winter.

Is there a config option to turn snow melting on?

**Comment by realGiB** [comment]
I am also having this issue

**Comment by ITCMD** [comment]
Is there any active development on this mod anymore?

**Comment by CorgiTaco** [comment]
I've been working on other projects and not feeling really up to work on this mod at this time tbh

**Comment by ITCMD** [comment]
Ok totally understand, it's a pretty game breaking bug so if it's possible to fix we'd all be very appreciative!

**Comment by ITCMD** [comment]
If you cant, you cant though and thats ok.

**Comment by ITCMD** [comment]
Not something you'll be able to fix @BjoernWesterholt, it's a bug in the mod. I'd talk to the folks on the Mod Dev discord and see if someone can make a new mod for ya

**Comment by YnwLNE** [comment]
Finally someone else expressed this. As stated before, it is pretty annoying and game breaking.

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
