### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CorgiTaco** [CorgiTaco/Better-Weather#85]
### Mod Version

aaaaaaaaaaaa

### Mod Loader

Forge

### Mod Loader Version

aaaaaaaaaaa

### What happened?

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

### latest.log

aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by NotStirred** [comment]
great bug corgi, maybe you should close it?
