### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ItsATrap11** [CorgiTaco/Better-Weather#87]
### Mod Version

2.0.1

### Mod Loader

Forge

### Mod Loader Version

36.1.65

### What happened?

As soon as a player would join the server (I tested this with only better weather installed), the server would immediately crash.

### latest.log

No crash logs were created, I even had to manually look for which mod was causing this crash in the first place

**Comment by CorgiTaco** [comment]
no information provided. And a latest.log is always present
