### ISSUE TITLE
how to disable seasons in latest versions?

### ISSUE THREAD

**Issue by Wedge1453** [CorgiTaco/Better-Weather#88]
### Mod Version

2.0.1

### Mod Loader

Forge

### Mod Loader Version

36.2,0

### What happened?

can't find where to disable seasons in configs, unlike older versions.

### latest.log

none

**Comment by ITCMD** [comment]
Also looking for something on this. I use Serene Seasons since it is more compatible with the Biomes a Plenty mod, and would like to disable this mod's seasons.

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
