### ISSUE TITLE
Seasons Server Crash

### ISSUE THREAD

**Issue by WenXin20** [CorgiTaco/Better-Weather#9]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Better Weather v1.1.0`

My server crashed while trying to join the world on client-side.
[Crash Report](https://gist.github.com/WenXin20/810b4781b20d8c185ee9a4ac7c911e84)

**Comment by CorgiTaco** [comment]
FIxed here: https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3145914

LMK if the issue persists
