### ISSUE TITLE
[Compatibility]: Better Weather stops New Tardis Mod from receiving its World Capabilities

### ISSUE THREAD

**Issue by 50ap5ud5** [CorgiTaco/Better-Weather#92]
### Mod Version

2.0.1

### Mod Loader

Forge

### Mod Loader Version

36.1.4

### What happened?

**Description**
BW stops the New Tardis Mod from attaching its ``TardisWorldProvider`` world capability from being properly attached.

For context, the New Tardis Mod dynamically creates new dimensions on the fly, and each dimension receives a world capability. 

This capability is used for many things, such as storing an ItemStackHandler instance for an ender-chest like global item inventory. Some blocks such as the Tardis Engine block in the New Tardis Mod use this capability to open a container that receives items from the global inventory.

For whatever reason, when BW is installed alongside New Tardis Mod, this capability is null. I'm not sure if this issue is caused by BetterWeather, or the way New Tardis Mod attaches their world capabilities.

**Steps to Reproduce**

_Production Environment_
1. Create a Forge Client installation for Minecraft 1.16.5 with Forge version 36.1.4 or above.
2. Install New Tardis Mod version 1.5.1 and Better Weather version 2.0.1.
3. Create a new world with Creative Mode (and therefore commands) enabled.
6. Run the command `/tardis create tardis:steampunk tardis:steam tardis:steam` to create a new "Tardis". This creates a new Dimension and attempts to attach the TardisWorldProvider capability. 
7. Right click the "Tardis" block and enter the door to go inside its interior dimension. 
8. Place down a Tardis Engine block inside this dimension. 
9. Right click any of the sides of this block.
10. See an ingame chat message similar to "You can only use this in a Tardis", that is the result of [the capability being missing](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/0ec5aec80d5796fcda72258c726880c780a330ca/src/main/java/net/tardis/mod/blocks/TardisEngineBlock.java#L65)

_Dev Environment_
1. Clone the [tag 1.5.1](https://gitlab.com/Spectre0987/TardisMod-1-14/-/tags/1.5.1) from the New Tardis Mod repo. Setup a Forge workspace with Forge version 36.1.4 or above.
2. Get Better Weather version 2.0.1 from Curse Maven and add it as a runtime dependency alongside the New Tardis Mod.
3. Comment out the Mekanism dependency in the build.gradle.
4. Refresh Gradle. run ./gradlew processResources if you are using Eclipse IDE. This is required because the New Tardis Mod's mods.toml file is populated by this task. For some reason Eclipse IDE will not run this gradle task after a gradle refresh, whilst Intellij will automatically do so.
5. Create a new world with Creative Mode (and therefore commands) enabled.
6. Run the command `/tardis create tardis:steampunk tardis:steam tardis:steam` to create a new "Tardis". This creates a new Dimension and attempts to attach the TardisWorldProvider capability. 
7. Right click the "Tardis" block and enter the door to go inside its interior dimension. 
8. Place down a Tardis Engine block inside this dimension. 
9. Right click any of the sides of this block.
10. If in a dev environment, place a breakpoint [at this line](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/0ec5aec80d5796fcda72258c726880c780a330ca/src/main/java/net/tardis/mod/blocks/TardisEngineBlock.java#L46).
11. See that the LazyOptional value is null.
12. See an ingame chat message similar to "You can only use this in a Tardis", that is the result of [the capability being missing](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/0ec5aec80d5796fcda72258c726880c780a330ca/src/main/java/net/tardis/mod/blocks/TardisEngineBlock.java#L65)

**References**
- New Tardis Mod's [attaching of its world capability](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/1.16/src/main/java/net/tardis/mod/events/CommonEvents.java#L251). 
- New Tardis Mod's use of the [TardisWorldProvider Capability being null when BW is installed](https://gitlab.com/Spectre0987/TardisMod-1-14/-/blob/1.16/src/main/java/net/tardis/mod/blocks/TardisEngineBlock.java#L46)
- Linked issue in [New Tardis Mod's issue tracker](https://gitlab.com/Spectre0987/TardisMod-1-14/-/issues/232).

### latest.log

[Latest Log from testing in a Dev environment with both mods installed ](https://gist.github.com/50ap5ud5/ec99d3edbb35db53fa1e0c3bd49cef10)

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
