### ISSUE TITLE
[Suggestion] Add Config Option For Enable/Disable Acid Rain Harming Leaves

### ISSUE THREAD

**Issue by Seikikai** [CorgiTaco/Better-Weather#93]
I See That The Acid Rain Been Damaging Forests Leaves Till Leaving Only Logs And Since Trees Doesn't Have A Mechanic For Regen Leafs Would Be Good An Option For Disable The Acid Rain Destroying The Leaves For Those Who Don't Want That The Ambient Get Heavily Damaged By Acid Rain.

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
