### ISSUE TITLE
CurseForge shows update available FROM 2.0.1 TO 1.2.7

### ISSUE THREAD

**Issue by Ghifari160** [CorgiTaco/Better-Weather#94]
### Mod Version

2.0.1

### Mod Loader

Forge

### Mod Loader Version

N/A

### What happened?

From the CurseForge launcher, a new "update" to this mod is "available." When the update button is pressed, the mod is actually downgraded back _FROM_ `2.0.1` _TO_ `1.2.7`. Creating a new pack from the CF launcher does download the correct version (`2.0.1`) but will _immediately_ show an update button, which "updates" to `1.2.7`.

### latest.log

Not applicable to this issue.

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
