### ISSUE TITLE
[Bug]: Acid rain won't affect player

### ISSUE THREAD

**Issue by ShrubRustle** [CorgiTaco/Better-Weather#96]
### Mod Version

1.2.9

### Mod Loader

Forge

### Mod Loader Version

35.1.37

### What happened?

All the other mechanics of acid rain work fine, and monsters/animals can be damaged by it just fine. "PLAYER" is 100% included in the config settings, so it's definitely not that. Images included to show the bug, as well as my config for the acid rain.
![image](https://user-images.githubusercontent.com/93964530/147894566-01275994-0ff9-4783-a31f-c6a045690a64.png)
![image](https://user-images.githubusercontent.com/93964530/147894675-ca0eef4b-f6f1-4dbe-8a3d-949f57581b1d.png)

### latest.log

[latest.log](https://github.com/CorgiTaco/Better-Weather/files/7800076/latest.log)

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
