### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Boy511** [CorgiTaco/Better-Weather#97]
### Mod Version

2.0.1

### Mod Loader

Forge

### Mod Loader Version

36.2.23

### What happened?

after i opened minecraft it says has class loading errors
![Screenshot 2022-01-31 160316](https://user-images.githubusercontent.com/98750309/151798492-cb282920-6fb8-4884-8e4c-63ba4b2885a8.png)

### latest.log

[latest.log](https://github.com/CorgiTaco/Better-Weather/files/7970838/latest.log)

**Comment by CorgiTaco** [comment]
Better Weather has been discontinued. If you want seasons please install [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) instead
